In [1]:
import numpy  as np

In [15]:
T = np.array([[1,0],[2,-1]])
C = np.array([[1,0],[1,1]])
T, C

(array([[ 1,  0],
        [ 2, -1]]),
 array([[1, 0],
        [1, 1]]))

In [16]:
Ci = np.linalg.inv(C)
Ci

array([[ 1.,  0.],
       [-1.,  1.]])

In [17]:
D = Ci @ T @ C
D

array([[ 1.,  0.],
       [ 0., -1.]])

T Cubic 

In [37]:
T = np.array([[1,0],[2,-1]])
T

array([[ 1,  0],
       [ 2, -1]])

In [41]:
T @ T @ T @ T @ T

array([[ 1,  0],
       [ 2, -1]])

In [29]:
C = np.array([[1,1],[1,2]])
Ci = np.linalg.inv(C)
d , _ = np.linalg.eig(T)
D = np.diag(d)

C, Ci, D

(array([[1, 1],
        [1, 2]]),
 array([[ 2., -1.],
        [-1.,  1.]]),
 array([[5., 0.],
        [0., 4.]]))

In [31]:
C @ D @ D @ D @ Ci

array([[186., -61.],
       [122.,   3.]])