In [1]:
import numpy as np

In [2]:
def gram_schmidt(A):
    """
    Perform the Gram-Schmidt process to orthogonalize the columns of matrix A.
    
    A : ndarray, shape (m, n)
        Input matrix whose columns will be orthogonalized.
    
    Returns:
    Q : ndarray, shape (m, n)
        Matrix with orthogonal columns (not normalized).
    """
    # Number of vectors (columns) in A
    m, n = A.shape
    
    # Initialize the matrix Q to store orthogonal vectors
    Q = np.zeros((m, n))
    
    # Iterate over each column vector in A
    for j in range(n):
        # Start with the original vector
        v = A[:, j]
        
        # Subtract projections onto all previous orthogonal vectors
        for i in range(j):
            # Project v onto Q[:, i]
            proj = np.dot(v, Q[:, i]) / np.dot(Q[:, i], Q[:, i]) * Q[:, i]
            v = v - proj
        
        # Store the orthogonalized vector in Q
        Q[:, j] = v
    
    return Q

In [3]:
def normalize(Q):
    """
    Normalize the columns of the matrix Q to obtain an orthonormal matrix.
    
    Q : ndarray
        Matrix with orthogonal columns.
    
    Returns:
    Q_normalized : ndarray
        Orthonormal matrix.
    """
    # Normalize each column vector in Q
    Q_normalized = np.zeros_like(Q)
    for i in range(Q.shape[1]):
        Q_normalized[:, i] = Q[:, i] / np.linalg.norm(Q[:, i])
    
    return Q_normalized

In [6]:
A = np.array([[1, 1, 1], [-1, 0, 1], [1, 1, 2]], dtype=float)
print("Original matrix A:")
print(A)

Original matrix A:
[[ 1.  1.  1.]
 [-1.  0.  1.]
 [ 1.  1.  2.]]


In [7]:
B = gram_schmidt(A)
B

array([[ 1.        ,  0.33333333, -0.5       ],
       [-1.        ,  0.66666667,  0.        ],
       [ 1.        ,  0.33333333,  0.5       ]])

In [27]:
b0 = B[:,0]
b0


array([ 1., -1.,  1.])

In [28]:
n0 = np.linalg.norm(b0)
n0

1.7320508075688772

In [29]:
V = np.array([[1,0,2,6],
              [0,1,8,2],
              [2,8,3,1],
              [1,-6,2,3]], dtype=np.float_)

In [31]:
U = gram_schmidt(V)
U  


array([[ 1.        , -1.66666667,  0.39920949,  3.52370252],
       [ 0.        ,  1.        ,  7.96047431, -0.13131811],
       [ 2.        ,  4.66666667, -0.51778656, -1.05054485],
       [ 1.        , -7.66666667,  0.63636364, -1.42261282]])

In [55]:
I = np.dot(V,U)
I

array([[ 11.        , -38.33333333,   3.18181818,  -7.11306409],
       [ 18.        ,  23.        ,   5.09090909, -11.38090254],
       [  9.        ,  11.        ,  63.56521739,   1.42261282],
       [  8.        , -21.33333333, -46.49011858,  -2.057317  ]])

In [60]:
I = V@U
I

array([[ 11.        , -38.33333333,   3.18181818,  -7.11306409],
       [ 18.        ,  23.        ,   5.09090909, -11.38090254],
       [  9.        ,  11.        ,  63.56521739,   1.42261282],
       [  8.        , -21.33333333, -46.49011858,  -2.057317  ]])

In [42]:
u = U[:,3]
u


array([ 3.52370252, -0.13131811, -1.05054485, -1.42261282])

In [43]:
n = np.linalg.norm(u)
n

3.944768129047296

In [44]:
u/n

array([ 0.89325973, -0.03328918, -0.26631346, -0.36063281])