In [3]:
import numpy as np

In [4]:
a = np.array([[1,1,1],[3,2,1],[2,1,2]])
a

array([[1, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [5]:
a_inv = np.linalg.inv(a)
a_inv

array([[-1.50000000e+00,  5.00000000e-01,  5.00000000e-01],
       [ 2.00000000e+00,  5.55111512e-17, -1.00000000e+00],
       [ 5.00000000e-01, -5.00000000e-01,  5.00000000e-01]])

In [6]:
s = np.array([15, 28, 23])
s

array([15, 28, 23])

In [8]:
c = np.dot(a_inv,s)
c

array([3., 7., 5.])

In [9]:
r = np.linalg.solve(a,s)
r

array([3., 7., 5.])