In [1]:
import numpy as np



In [2]:
v = np.array([3, 4])
v

array([3, 4])

In [3]:
v.T

array([3, 4])

In [4]:
u = np.array([3, 4])
v = np.array([1, 2])
result_add = u + v
result_sub = u - v
result_add, result_sub

(array([4, 6]), array([2, 2]))

In [5]:
k = 2
result_scalar_mult = k * v
result_scalar_mult

array([2, 4])

In [6]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
cross_product = np.cross(u, v)
cross_product

array([-3,  6, -3])

In [7]:
r = np.array([3,2])
s = np.array([-1,2])
p = np.dot(r,s)
p


1

In [8]:
# Vectors
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# Dot product
dot_product = np.dot(u, v)

# Magnitude squared of u
magnitude_u_squared = np.dot(u, u)

# Projection of v onto u
projection = (dot_product / magnitude_u_squared) * u

print("Projection of v onto u:", projection)

Projection of v onto u: [2.28571429 4.57142857 6.85714286]


In [9]:


# Define the vector
vector = np.array([1,2,3, 4])

# Calculate the length (magnitude) of the vector
length = np.linalg.norm(vector)

print("Length of the vector:", length**2)

Length of the vector: 30.0


In [10]:
r = np.array([3, -4, 0])
s = np.array([10,5,-6])

# Calculate dot product of a and b
dot_product = np.dot(r, s)

# Calculate the magnitude (length) of vector b
magnitude_r = np.linalg.norm(r)

# Calculate the scalar projection of a onto b
scalar_projection = dot_product / magnitude_r

print("Scalar projection of a onto b:", scalar_projection)

dot_product , magnitude_r

Scalar projection of a onto b: 2.0


(10, 5.0)

In [11]:
# Define vectors a and b
a = np.array([1, 2, -1])
b = np.array([3, -4, 5])
c = np.array([1, -8, 7])

# Compute the determinant (for 2D vectors)
determinant = np.linalg.det(np.array([a, b, c]))

if determinant == 0:
    print("The vectors are linearly dependent.")
else:
    print("The vectors are linearly independent.")

The vectors are linearly dependent.
